name: Test

on:
  pull_request:
    types: [opened, synchronize]
        
jobs:
  changes:
    name: "changes"
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "${{ github.event.pull_request.head.ref }}"
          echo "ok"
