name: Test

on:
  pull_request:
    branches: [ main ]
    types: [ assigned, opened, edited, reopened, synchronize ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Push changes
        run: |
          echo "TASK_ID=$(
            clearml-task --project 'Github CICD Video' --name cicd_test --branch ${{ github.head_ref }} --script task.py --requirements requirements.txt --skip-task-init --queue default | rg -o 'Task id=(.*) sent' -r '$1'
          )" >> $GITHUB_OUTPUT
