name: Pre-delete Translation

on:
  workflow_run:
    workflows: ["trigger"]
    types: 
      - requested
        
jobs:
  changes:
    name: "changes"
    runs-on: ubuntu-latest
    steps:
      - name: echo github context
        if: always()
        run: echo "${{ github.event.workflow_run.head_repository.full_name }}-${{ github.event.workflow_run.head_branch }}-${{ github.workflow_ref }}"
