name: Test

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Push changes
        run: >
          gh release create --target ${{
          github.event.pull_request.merge_commit_sha }} {--title=CML\
          ,}$(basename ${{ github.head_ref }}) --generate-notes --draft
