name: Test

on:
  pull_request:
    types: [labeled]
        
jobs:
  changes:
    name: "changes"
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "${{ github.event.pull_request.head.label }}"
