name: Test

on:
  pull_request:
    types: [closed]
        
jobs:
  changes:
    name: "changes"
    runs-on: ubuntu-latest
    steps:
      - name: test
      - run: >
          gh release create --target ${{
          github.event.pull_request.merge_commit_sha }} {--title=CML\
          ,}$(basename ${{ github.head_ref }}) --generate-notes --draft
