name: Pre-delete Translation

on:
  pull_request: 
        
jobs:
  changes:
    name: "changes"
    runs-on: ubuntu-latest
    steps:
      - name: echo github context
        if: always()
        run: echo "${{github.event.inputs.commitMessage}}"
