name: Test

on:
  issue_comment:
    types:
      - created
        
jobs:
  changes:
    name: "changes"
    runs-on: ubuntu-latest
    steps:
      - name: Display Branch Information
        run: |
          echo "${{github.event.pull_request}}"
          echo "${{github.event.issue.pull_request.url}}"
          echo "${{github.event.issue.pull_request}}"
          echo "${{github.event.pull_request.url}}"
