name: Test

on:
  pull_request:
    paths:
      - requirements.txt
  push:
    branches:
      - main
        
jobs:
  changes:
    name: "changes"
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "${{github.event.pull_request.head.repo.full_name}}"
          echo "ok"
