name: Test

on:
  pull_request:
    types: [opened, synchronize]
        
jobs:
  changes:
    name: "changes"
    runs-on: ubuntu-latest
    steps:
      - name: test
        env:
          REF: ${{ github.event.pull_request.head.ref }}
        run: |
          echo $REF
          echo "ok"
