name: Test

on:
  pull_request:
  issues:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Push changes
        env:
          TEST: ${{ github.event.issue.title }}
        run: echo $TEST
