name: Test

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - unlabeled
      - opened
      - synchronize
      - reopened

jobs:
  check-changesets:
    if: |
      !contains(github.event.pull_request.labels.*.name, '🤖Skip Major Check')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout the feature branch
        run: git checkout ${{ github.head_ref }} --
