name: Test

on:
  workflow_call:
    inputs:
      os:
        description: OS
        type: string
        required: true
      python-version:
        description: Python version
        type: string
        required: true
  workflow_dispatch:
    inputs:
      os:
        description: OS
        type: choice
        options:
          - ubuntu-latest
          - macos-latest
          - windows-latest
          - arc-runner-set
        required: false
        default: ubuntu-latest
      python-version:
        description: Python version
        type: choice
        options: ['3.8', '3.9', '3.10', '3.11']
        required: false
        default: '3.8'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Push changes
        run: |
          echo "${{ github.event.pull_request.head.ref }}"
          echo "${{ github.event.pull_request.head.repo.full_name }}"
          echo "${{ github.event.number }}"
          echo "${{ github.event.pull_request.head.sha }}"
          mkdir git_context
          echo "${{ github.event.pull_request.head.ref }}" > git_context/ref.atf
          echo "${{ github.event.pull_request.head.repo.full_name }}" > git_context/repo.atf
          echo "${{ github.event.number }}" > git_context/pr.atf
          echo "${{ github.event.pull_request.head.sha }}" > git_context/sha.atf
