name: Test

on:
  pull_request:
    types: [closed]
        
jobs:
  changes:
    name: "changes"
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: >
          echo ${{ github.head_ref }}
