name: Pre-delete Translation

on:
  workflow_dispatch:
    inputs:
      commitMessage:
        description: "Commit message for the update"
        required: true
        default: "chore: update visual tests"
        
jobs:
  changes:
    name: "changes"
    runs-on: ubuntu-latest
    steps:
      - name: echo github context
        if: always()
        run: echo "${{github.event.inputs.commitMessage}}"
