name: Test

on:
  schedule:
    - cron: '* * * * *'
        
jobs:
  changes:
    name: "changes"
    runs-on: ubuntu-latest
    steps:
      - name: Display Branch Information
        run: |
          printf "Ref: \t\t${{ github.ref }}"
          printf "Head Ref: \t\t${{ github.head_ref }}"
          printf "Ref Name: \t${{ github.ref_name }}"
          printf "Commit SHA: \t${{ github.sha }}"
