name: Test

on:
  pull_request:
    paths:
      - path1/path2/
        
jobs:
  changes:
    name: "changes"
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "${{github.head_ref}}"
          echo "ok"
