name: Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Push changes
        run: |
          echo "${{ github.event.pull_request.head.ref }}"
          echo "${{ github.event.pull_request.head.repo.full_name }}"
          echo "${{ github.event.number }}"
          echo "${{ github.event.pull_request.head.sha }}"
          mkdir git_context
          echo "${{ github.event.pull_request.head.ref }}" > git_context/ref.atf
          echo "${{ github.event.pull_request.head.repo.full_name }}" > git_context/repo.atf
          echo "${{ github.event.number }}" > git_context/pr.atf
          echo "${{ github.event.pull_request.head.sha }}" > git_context/sha.atf
