name: React to Label

on:
  pull_request:
    types: [labeled]

jobs:
  label_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Print label added
        run: |
          echo "A label was added: ${{ github.event.pull_request.head.label }}"
